#+TITLE: Taylor vs Fourier
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="https://gongzhitaao.org/orgcss/org.css"/>

[[http://dev.ipol.im/~coco/website/taylorfourier.html#:~:text=When%20x%20and%20%CE%B8%20are,a%20sum%20of%20sinusoidal%20waves.][Taylor and fourier are the same]]

- taylor series
$$
f(x)=c_0+c_1x+c_2x^2+c_3x^3+\cdots
$$

- Fourier series
$$
g(\theta)=c_0+c_1\exp(i\theta)+c_2\exp(2i\theta)+c_3\exp(3i\theta)+\cdots
$$


- they are the same thing in complex numbers
$$
f(z)=c_0+c_1z+c_2z^2+c_3z^3+\cdots
$$

- restrict z to real axis, i.e. z = x, obtain Taylor series of f

- restrict z to unit circle $z = e^{i\theta}$ - obtain fourier series of function $g(\theta) = f(e^{i\theta})$

- https://math.stackexchange.com/questions/7301/connection-between-fourier-transform-and-taylor-series
-
  #+BEGIN_QUOTE
https://math.stackexchange.com/a/7380
There is an analogy, more direct for fourier series. Both Fourier series and Taylor series are decompositions of a function f(x), which is represented as a linear combination of a (countable) set of functions. The function is then fully specified by a sequence of coefficients, instead of by its values f(x) for each x. In this sense, both can be called a transform f(x)↔{a0,a1,...}

For the Taylor series (around 0, for simplicity), the set of functions is {1,x,x2,x3...}. For the Fourier series is {1,sin(ωx),cos(ωx),sin(2ωx),cos(2ωx)...}.

Actually the Fourier series is one the many transformations that uses an orthonomal basis of functions. It is shown that, in that case, the coefficients are obtained by "projecting" f(x) onto each basis function, which amounts to an inner product, which (in the real scalar case) amounts to an integral. This implies that the coefficients depends on a global property of the function (over the full "period" of the function).

The Taylor series (which does not use a orthonormal basis) is conceptually very different, in that the coeffients depends only in local properties of the function, i.e., its behaviour in a neighbourhood (its derivatives).
#+END_QUOTE
